<a href="https://colab.research.google.com/github/irahanjose/Aprendizaje-de-M-quina-con-Python/blob/main/02_IntroNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lo esencial de Numpy para Deep Learning

In [ ]:
import numpy as np

## 1. Vectores

In [ ]:
# Vector fila de 1x20
vector_fila = np.arange(0,20)
print(vector_fila)
type(vector_fila)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


numpy.ndarray

In [ ]:
# Características (tamaño, tipo de datos)
print(vector_fila.shape)
print(type(vector_fila))
print(vector_fila.dtype) # Se puede acceder a las opciones de "vector" escribiendo vector. y oprimiendo "Tab"

(20,)
<class 'numpy.ndarray'>
int64


In [ ]:
# Funciones útiles
print(vector_fila.mean())
print(vector_fila.max())

9.5
19


In [ ]:
# Convertirlo en vector columna (reshape)
vector_columna = vector_fila.reshape(20,1)
print(vector_columna)
print(vector_columna.shape)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]
(20, 1)


## 2. Matrices

In [ ]:
# Matrix de 5 filas x 4 columnas con números aleatorios
matriz = np.random.randn(5,4)
print(matriz)

[[ 1.20882452  1.08504046 -0.5063634  -0.7442248 ]
 [-0.4557556   0.12779684  1.69176772 -1.64302223]
 [-1.1302146   0.06707312  1.62445974  0.46378129]
 [-0.45895427 -0.44021354  0.66630988 -1.30696795]
 [ 1.28186455 -1.16914498 -0.570579   -1.25359861]]


In [ ]:
print(matriz.shape)
print(type(matriz))
print(matriz.dtype)

(5, 4)
<class 'numpy.ndarray'>
float64


In [ ]:
# Al igual que con los vectores se pueden calcular parámetros como mean, std, max, min. Pero en este caso
# se debe especificar si es por filas, por columnas o el cálculo sobre todo el arreglo
matriz.mean?

In [ ]:
print(matriz.mean(axis=0)) # Promedio de cada columna

[-0.11488058  0.02554805 -0.26765019  0.22906841]


In [ ]:
print(matriz.mean(axis=1)) # Promedio de cada fila

[-0.11287971  0.62793144 -0.4620235  -0.2577885   0.04486739]


In [ ]:
print(matriz.mean()) # Convertir la matriz en un vector (matriz[:]) y calcular la media

-0.07310604247735171


In [ ]:
# Transpuesta de una matriz: (5,4) -> (4,5)
matriz_T = matriz.T
print(matriz)
print(matriz_T)

[[ 0.33236584  0.28144676 -1.13466725  0.06933583]
 [ 0.94538246  1.32099067 -0.45666187  0.70201449]
 [-1.41586204  0.35916566 -0.01862525 -0.77277237]
 [-0.28121434 -0.54329848 -0.51251452  0.30587335]
 [-0.15507481 -1.29056435  0.78421796  0.84089076]]
[[ 0.33236584  0.94538246 -1.41586204 -0.28121434 -0.15507481]
 [ 0.28144676  1.32099067  0.35916566 -0.54329848 -1.29056435]
 [-1.13466725 -0.45666187 -0.01862525 -0.51251452  0.78421796]
 [ 0.06933583  0.70201449 -0.77277237  0.30587335  0.84089076]]
